name: Weekly Gumroad Report

on:
  schedule:
    - cron: '0 10 * * 1'  # Every Monday 10:00 UTC
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run report script
        env:
          GUMROAD_TOKEN: ${{ secrets.GUMROAD_TOKEN }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: python weekly_report.py
